### ISSUE TITLE
publicKeyJwk

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/universal-resolver#103]
When using the context `https://www.w3.org/ns/did/v1`, the universal resolver seems to remove the publicKeyJwk contents. 

I assume there isn't full support for JSON-LD 1.1 and `@json` in the DID document parser.

**Comment by troyronda** [comment]
Related comments:

- https://github.com/decentralized-identity/context/issues/3#issuecomment-578611789
- https://github.com/decentralized-identity/universal-resolver/issues/77#issuecomment-578429078

**Comment by OR13** [comment]
I believe this should be resolved now... since https://github.com/w3c/did-spec-registries/blob/master/vocabs/v1/context.jsonld#L62

**Comment by peacekeeper** [comment]
We looked at this on the [14 Jul 2021 Universal Resolver call](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#special-work-item-calls) and believe this can be closed, since the Universal Resolver should have full support for JSON-LD 1.1 by now. Also see comment https://github.com/decentralized-identity/universal-resolver/issues/76#issuecomment-871600434.
