### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by haroldship** [decentralized-identity/universal-resolver#18]
I tried forking this repo, then cloning to my MacBook and running `cd universal-resolver/implementations/java/` followed by `docker-compose -f docker-compose.yml build`

The build fails (maven, java) with many errors, beginning with:
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ uni-resolver-driver-did-btcr ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /opt/uni-resolver-java/driver-did-btcr/src/main/resources
[INFO] skip non existing resourceDirectory /opt/uni-resolver-java/driver-did-btcr/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ uni-resolver-driver-did-btcr ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /opt/uni-resolver-java/driver-did-btcr/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /opt/uni-resolver-java/driver-did-btcr/src/main/java/uniresolver/driver/did/btcr/bitcoinconnection/BitcoinjSPVBitcoinConnection.java:[7,54] cannot find symbol
  symbol:   class Chain
  location: class info.weboftrust.txrefconversion.TxrefConverter

**Comment by peacekeeper** [comment]
Thanks for reporting, I fixed that in my fork, waiting for the PR to be merged, in the meantime you can try this fork: https://github.com/peacekeeper/universal-resolver/

**Comment by haroldship** [comment]
Hi @peacekeeper 
I pulled from your fork and it indeed fixes the build.
Thanks!
However, I am following your [blog](https://medium.com/decentralized-identity/a-universal-resolver-for-self-sovereign-identifiers-48e6b4a5cc3c) and there are runtime errors accessing some of the identities.

Should I open another issue?

In particular:

did:sov:WRfXPg8dantKVubE3HX8pw **OK**

**Resolution problem for did:btcr:xkrn-xzcr-qqlv-j6sl: Driver reported for did:btcr:xkrn-xzcr-qqlv-j6sl: RPC Query Failed (method: getblockhash, params: [1156667])**

**Resolution problem for did:v1:testnet:5431fafa-a38f-4e37-96b6-cdeb8e5d1d40: Cannot retrieve RESOLUTION RESULT for did:v1:testnet:5431fafa-a38f-4e37-96b6-cdeb8e5d1d40 from https://genesis.testnet.veres.one/dids/did:v1:testnet:5431fafa-a38f-4e37-96b6-cdeb8e5d1d40: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed**

did:ipid:QmbFuwbp7yFDTMX6t8HGcEiy3iHhfvng89A19naCYGKEBj **Does not return**

did:uport:2ok9oMAM54TeFMfLb3ZX4i9Qu6x5pcPA7nV **OK**

did:stack:v0:16EMaNw3pkn3v6f2BgnSSs53zAKH4Q8YJg-0 **OK**

**Comment by peacekeeper** [comment]
Hello again,

Thanks again for testing. There are different reasons why some of the DIDs are failing for you:

- For *did:btcr*, the driver is configured by default to connect to a local instance of bitcoind. You can see the configuration of the resolver and all drivers here:

https://github.com/decentralized-identity/universal-resolver/blob/master/implementations/java/docker-compose.yml

So you could either install a local bitcoind instance. Or alternatively, if you change one line, you can resolve *did:btcr* via an external block explorer (Blockcypher API) rather than your own local bitcoind instance:

```
services:
  driver-did-btcr:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-driver-did-btcr
      args:
        bitcoinConnection: blockcypherapi
```

(we need to document this better)

- For *did:v1* apparently a certificate on the Veres One testnet ledger node is expired, they need to fix that, then it should work. It's not a bug with the resolver itself.

- For *did:ipid* that particular DID seems to have been deleted. I'll try to find another one that works and update the example.

**Comment by peacekeeper** [comment]
Update: The *did:v1* examples should work now, see https://github.com/veres-one/veres-one/issues/16

**Comment by haroldship** [comment]
thanks I will close this now
