### ISSUE TITLE
Spring Security DID-based Authentication Provider

### ISSUE THREAD

**Issue by pepoospina** [decentralized-identity/universal-resolver#37]
We want to integrate DID-based authentication as an **optional** authentication method to our platform, which uses Spring Security.

For this, we plan to add a new authentication provider and integrate the Java-based did universal resolver.

Has anyone already started working on this? Any advice?

**Comment by creatornader** [comment]
Hello Jose! I'm one of the maintainers of the Universal Resolver so let me see if I can answer your questions.

As you may know, currently the Universal Resolver does not directly support authentication of the user. My recommendation would be to implement a new DID-based authentication provider into your platform, using the Java library to resolve DIDs and get keys & service endpoints (probably prior to authentication). This is fairly similar to what you have spelled out. I'm not actively involved in DID Auth implementations at the moment, but I am happy to answer any questions you have about the Java library. A quick search [here](https://github.com/decentralized-identity/) finds a few repositories dedicated to address DID Auth, not just DID resolution (may be helpful as a starting point).

More info on the Java library can be found [here](https://github.com/decentralized-identity/universal-resolver/tree/master/resolver/java). Since Spring is a native Java platform, you will want invoke the library via the "Local Resolver" or "Client Resolver" options. Depending on your use cases and requirements one may have advantages over the other (the basic trade off is running drivers locally vs calling a remote web API).
