### ISSUE TITLE
DID Protocol Version Support

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/universal-resolver#41]
Many DID Methods are currently under development or experimental...

Some use Blockchain Testnets, others use Mainnets.

I'd like to establish more clarity around how the universal resolver can support less stable DIDs in a way that does not create confusion or security issues.

One thought I had was to allow for simple resolver proxying, so that the universal resolver for "did:highly-experimental:123" might just call another http service which would be responsible for managing version changes.

This way we do not need to be publishing frequent changes to universal resolver for things that have not even stabilized yet.

Is this acceptable approach?

**Comment by peacekeeper** [comment]
Yes this makes total sense, and the Universal Resolver actually already supports this kind of architecture where it can simply call another remote resolver instead of invoking a local Docker container. This is similar to how DNS servers sometimes rely on other DNS servers for lookups.

In the [configuration file](https://github.com/decentralized-identity/universal-resolver/blob/master/config.json) some entries have an `image` field (for Dockerized drivers), and some entries have a `url` field (for retrieving DID Documents via HTTP).

In fact `did:v1` and `did:ipid` currently already work that way - the Universal Resolver simply calls a remote HTTP endpoint for retrieving the DID Document. Of course this has trust implications.

In the DID Resolution spec there are some early thoughts on different Resolver architectures:
https://w3c-ccg.github.io/did-resolution/#architectures

We also need to keep track of driver versions. This is supposed to happen here but unfortunately is not very well maintained yet:
https://github.com/decentralized-identity/universal-resolver#drivers

**Comment by OR13** [comment]
@peacekeeper thanks! these are super helpful. I have no excuse not to open some PRs and finish the documentation.
